<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "z3_fasapi"
 *
 * Auto generated by Extension Builder 2014-08-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'z3 Fas api',
	'description' => 'API to connect Seminarmgr with TYPO3 via eID',
	'category' => 'plugin',
	'author' => 'Sven Külpmann',
	'author_email' => 'sven.kuelpmann@lenz-wie-fruehling.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);